import { lazy } from 'react'

const loadIcon = (icon: string) =>
  lazy(() => import(`./assets/svgs/${icon}.svg?react`))

export const icons = {
  'arrow-back-outline': loadIcon('arrow-back-outline'),
  'arrow-down-outline': loadIcon('arrow-down-outline'),
  'arrow-forward-outline': loadIcon('arrow-forward-outline'),
  'arrow-ios-back-outline': loadIcon('arrow-ios-back-outline'),
  'arrow-ios-forward-outline': loadIcon('arrow-ios-forward-outline'),
  'arrow-up': loadIcon('arrow-up'),
  block: loadIcon('block'),
  bookmark: loadIcon('bookmark'),
  'bookmark-outline': loadIcon('bookmark-outline'),
  calendar: loadIcon('calendar'),
  'calendar-outline': loadIcon('calendar-outline'),
  'checkmark-outline': loadIcon('checkmark-outline'),
  'close-outline': loadIcon('close-outline'),
  'color-palette-outline': loadIcon('color-palette-outline'),
  'done-all-outline': loadIcon('done-all-outline'),
  'expand-outline': loadIcon('expand-outline'),
  eye: loadIcon('eye'),
  'eye-off': loadIcon('eye-off'),
  'eye-off-outline': loadIcon('eye-off-outline'),
  'eye-outline': loadIcon('eye-outline'),
  facebook: loadIcon('facebook'),
  'fill-bell': loadIcon('fill-bell'),
  github: loadIcon('github'),
  google: loadIcon('google'),
  home: loadIcon('home'),
  'home-outline': loadIcon('home-outline'),
  image: loadIcon('image'),
  'image-outline': loadIcon('image-outline'),
  layers: loadIcon('layers'),
  'layers-outline': loadIcon('layers-outline'),
  'log-out-outline': loadIcon('log-out-outline'),
  'menu-outline': loadIcon('menu-outline'),
  'message-circle': loadIcon('message-circle'),
  'message-circle-outline': loadIcon('message-circle-outline'),
  mic: loadIcon('mic'),
  'mic-outline': loadIcon('mic-outline'),
  'more-horizontal-outline': loadIcon('more-horizontal-outline'),
  'outline-bell': loadIcon('outline-bell'),
  'paper-plane-outline': loadIcon('paper-plane-outline'),
  'pause-circle': loadIcon('pause-circle'),
  'pause-circle-outline': loadIcon('pause-circle-outline'),
  person: loadIcon('person'),
  'person-add': loadIcon('person-add'),
  'person-add-outline': loadIcon('person-add-outline'),
  'person-outline': loadIcon('person-outline'),
  'person-remove': loadIcon('person-remove'),
  'person-remove-outline': loadIcon('person-remove-outline'),
  'play-circle': loadIcon('play-circle'),
  'play-circle-outline': loadIcon('play-circle-outline'),
  'plus-circle': loadIcon('plus-circle'),
  'plus-circle-outline': loadIcon('plus-circle-outline'),
  'plus-square': loadIcon('plus-square'),
  'plus-square-outline': loadIcon('plus-square-outline'),
  'radio-button-checked': loadIcon('radio-button-checked'),
  'radio-button-unchecked': loadIcon('radio-button-unchecked'),
  recaptcha: loadIcon('recaptcha'),
  'search-outline': loadIcon('search-outline'),
  settings: loadIcon('settings'),
  'settings-outline': loadIcon('settings-outline'),
  'trending-up-outline': loadIcon('trending-up-outline'),
}
