name: Publish npm package

on:
  push:
    branches:
      - chore/BD-63-automating-npm-publish

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Setup pnpm
        run: |
          npm install -g pnpm
          pnpm config set registry https://registry.npmjs.org/

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Bump version and commit
        run: |
          pnpm version patch
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json pnpm-lock.yaml
          git commit -m "ci: bump version"
          git push

      - name: Push tags
        run: git push --follow-tags

      - name: Publish to npm
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}